# Generated by Django 2.0.7 on 2018-08-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='文章标题', max_length=50)),
                ('date', models.DateField()),
                ('image', models.ImageField(default='default.jpg', upload_to='image/')),
                ('text', models.TextField(default='正文')),
            ],
        ),
    ]
