# Generated by Django 2.1.2 on 2018-10-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_door_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
