# Generated by Django 2.1.8 on 2019-11-13 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20180910_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['last_mod_time'], 'verbose_name': '项目名称', 'verbose_name_plural': '项目列表'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='url',
            field=models.CharField(default='项目链接', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.CharField(default='项目简介', max_length=300),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='项目标题', max_length=100),
        ),
        migrations.AlterModelTable(
            name='gallery',
            table='gallery',
        ),
    ]
